### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by trandinh135** [perliedman/geojson-path-finder#10]
I had a linestring layer and a point layer on the same map area. I replace my linestring to your demo, it work with any position of marker. Then I build node js server. I find path between two points in my point layer. Its not working at all
Simply: my points 111.01234567891011, 11.01234567891011 -  222.01234567891011, 22.01234567891011 
if change any number after 5 or 6 it work, before not.
I try change _precision e-5 to e-2. it work but points of path result aren't serial

![screenshot_1](https://cloud.githubusercontent.com/assets/16321340/21337849/744b9710-c6a3-11e6-8c78-e6f61535403b.png)

**Comment by perliedman** [comment]
Hi @trandinh135, sorry to hear this isn't working out for you. However, I have a hard time understanding the actual problem here. Ideally, provide a running example of what you're trying to do, or at least provide a dataset (GeoJSON network) that illustrates the problem.

Without seeing more, it's really hard to tell what the problem might be.

**Comment by trandinh135** [comment]
I solved its by call turf-nearest  point from myPoint to allPoint before call findPath.
 You can try with my data(build in nodejs server) ,path data from path.json , two points from points.json
[path_points.zip.txt](https://github.com/perliedman/geojson-path-finder/files/663749/path_points.zip.txt)

**Comment by Rishi341** [comment]
Hi !. @perliedman  , facing the same problem as above. Here is my dataset attached. Please illustrate me with an example as i am a newbie to Node JS. 


[DataSet.txt](https://github.com/perliedman/geojson-path-finder/files/679660/DataSet.txt)

**Comment by perliedman** [comment]
@Rishi341 a common problem, as hinted by @trandinh135, is that you attempt to pass `start` or `finish` coordinates that are not part of the routing network.

You can use for example `turf-nearest` to find the closest point in the network, and the pass that as `start` or `finish`, that is what the demo does.

**Comment by perliedman** [comment]
@s9eenk 

```js
var explode = require('turf-explode');
var nearest = require('turf-nearest');
var PathFinder = require('geojson-path-finder');

var pathFinder = new PathFinder(geojson);
var points = explode(geojson);

var start = point(...);
var end = point(...);

var startInNetwork = nearest(start, points);
var endInNetwork = nearest(end, points);

var path = pathFinder.findPath(startInNetwork, endInNetwork);
```

**Comment by s9eenk** [comment]
Superb !. . . .Saved my day. Perfect
