### ISSUE TITLE
weight to km

### ISSUE THREAD

**Issue by trandinh135** [perliedman/geojson-path-finder#19]
How can i calculate real distance from weight ?

**Comment by perliedman** [comment]
Hi,

it depends entirely on how you configured the weights of your graph. By default, GeoJSON Path Finder will use distance as weight (https://github.com/perliedman/geojson-path-finder/blob/master/preprocessor.js#L10), so no calculation is necessary, just take the weight and it will be the total distance.

If you have other weights, it is still quite easy to just loop over the returned `coordinates` and sum the distance between them.
