### ISSUE TITLE
[compactor] strange result when trying to reach a removed (compacted) node

### ISSUE THREAD

**Issue by bertrandmd** [perliedman/geojson-path-finder#27]
Hi !

I've a strange issue, and I need to shortcut the compactor to resolve it.

this is my network, and displayed points are nodes who are removed by compactor: [(here)](https://github.com/perliedman/geojson-path-finder/blob/master/compactor.js#L85-L91)
![capture d ecran 2018-01-23 a 11 55 18](https://user-images.githubusercontent.com/9257198/35273064-8029c542-0037-11e8-92e1-f237a6ef569f.png)

this is my expected path result:
![capture d ecran 2018-01-23 a 11 57 32](https://user-images.githubusercontent.com/9257198/35273228-249ed34c-0038-11e8-8ece-06358eab0bda.png)

this is what I get:
![capture d ecran 2018-01-23 a 11 57 45](https://user-images.githubusercontent.com/9257198/35273614-723764d8-0039-11e8-81de-d28bae99d584.png)

I've checked some relations : 
![capture d ecran 2018-01-23 a 12 34 51](https://user-images.githubusercontent.com/9257198/35273914-83e2b16e-003a-11e8-94ea-b8e44a862488.png)

Do you think it's an issue ? ~~or it is simply impossible to access these compacted/removed nodes ?~~

EDIT : access to compacted/removed node seems to be purpose of `_createPhantom()` method, so we have an issue 

thanks for your support and your library !

Bertrand

**Comment by bertrandmd** [comment]
this issue is only on destination. (if I reverse my route, I have the expected result)

**Comment by perliedman** [comment]
Hi,
interesting. I'm not entirely sure when I will have the time to dig into this, but if it would be possible for you to share the network you're using (possibly just the part you're showing here) and the actual waypoints you use to cause this problem, it would be very helpful.

The best way to track things like this down is usually to add a new test to the library and go from there.

**Comment by taneltm** [comment]
Ran into the same issue. Happened exactly the same way and reversing the route displayed correct results.
I might take a look at the issue again if a similar issue happens again.

For now I solved the issue by using turf.js and splitting my routing network lines into smaller chunks.
https://turfjs.org/docs/#lineChunk
After doing that, the created routes seemed correct.

**Comment by perliedman** [comment]
A PR with a failing test case would be very welcome! (A PR with a working fix is of course even more welcome...)

**Comment by reyemtm** [comment]
@taneltm can you elaborate I am getting similar results with these "shortcuts" appearing, and not just at the end of the paths. If I cut it into 2 foot chun

@perliedman all I really need returned is the ids of the original network features that make up the shortest path, I can then build the route from those, and it would seem this would be possible with the edgedata function but I cant get the edgeDatas to return anything

**Comment by perliedman** [comment]
Fixed by #70, released in 1.5.3.
