### ISSUE TITLE
Can't find route.

### ISSUE THREAD

**Issue by devilop3rz** [perliedman/geojson-path-finder#5]
Hi, 
i found your great tool to create a Router on existing geoJSON-Paths.
It worked most of the time, but sometimes I get the Error "Cant't find route".  I checked the lines for spaces and other errors but i can't find any. Are there any size limits for processing?

I have uploaded my file for testing,:
[test.zip](https://github.com/perliedman/geojson-path-finder/files/484675/test.zip)

**Comment by perliedman** [comment]
Although the lines cross at the three way intersection roughly in the middle of your network, it appears there are no nodes (coordinates) sufficiently close to each other on the crossing segments.

The topology can only be built if the router can snap coordinates close to each other to a node, to figure out which segments are reachable from each other.

It should be enough to insert new coordinates into the two line strings to make sure they have a coordinate in common.

**Comment by perliedman** [comment]
You can also work around this without modifying your data by passing the option `precision: 1e-4` when you create the network. The result currently looks pretty horrible, though.

**Comment by devilop3rz** [comment]
Thanks for your help! Editing the precision fixed my problems :)
