### ISSUE TITLE
ES6 Standards and 'Could not find declaration file for module geojson-path-finder'

### ISSUE THREAD

**Issue by N0TARNI3** [perliedman/geojson-path-finder#72]
Hi. Would it be okay to integrate ES6 standards for client-side-server browsers that can't recognize the require() function? Also, I can't seem to fix the issue 'Could not find declaration file for module geojson-path-finder'. I'm a beginner at javascript language, I tried to look for solutions but I can't make it work. Hope you can help me on this one. Godspeed!

**Comment by crizzis** [comment]
Please see provided [PR](https://github.com/perliedman/geojson-path-finder/pull/76)

**Comment by perliedman** [comment]
Version 2.0.0 uses ESM in the source and should hopefully be possible to use directly from the client side.
