### ISSUE TITLE
Never finds a path

### ISSUE THREAD

**Issue by psociety** [perliedman/geojson-path-finder#73]
ty for creating pathFinder!

**Version:** 1.5.3
**Demo:** https://jsfiddle.net/6qugy0rm/

I made a simple GeoJSON and i tried to apply the pathFinder but i never get a path :s
![image](https://user-images.githubusercontent.com/29523682/124159052-f7137b80-da9a-11eb-9f5d-8b10b9508562.png)
(a red path would be painted between those markers if pathFinder had any result)

What i'm missing out?

**Comment by perliedman** [comment]
Hi, a late reply, but it looks like your start and end coordinates are not part of the graph. I should update the docs, but start and end must be vertices in the routing network.

A common solution is to snap start and end to the closest vertex in the routing network before calling `findPath`.
