### ISSUE TITLE
openlayers

### ISSUE THREAD

**Issue by trandinh135** [perliedman/geojson-path-finder#8]
Can I using your lib with openlayers and my geojson data

**Comment by perliedman** [comment]
@trandinh135 yes, definitely. There's nothing stopping you from using geojson-path-finder with any mapping library (or other library, for that matter). You can use it in the browser, with Leaflet, with OpenLayers, or you can use it on the server with Node.js. There's no graphical/UI elements in geojson-path-finder, so it isn't tied to anything in particular.
