### ISSUE TITLE
2.x include 1.5.3?

### ISSUE THREAD

**Issue by pbvahlst** [perliedman/geojson-path-finder#80]
Will the changes from 1.5.3 find its way into 2.x?

Thanks for a nice path finder

**Comment by perliedman** [comment]
Hi, what changes in particular are you thinking about?

**Comment by pbvahlst** [comment]
This fix in particular https://github.com/perliedman/geojson-path-finder/pull/70

**Comment by perliedman** [comment]
Thanks, good catch, I wasn't aware I accidentally did the 2.0 work without that commit. I have pushed a fix that includes it to `master`. Will hold off a while to check if there are more issues in 2.0.0 and then push a 2.0.1.
